version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c 'yarn start'
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=development
    tty: true
